version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    main: .
    binary: infai
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: linux-arm64
    main: .
    binary: infai
    goos: [linux]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: darwin-amd64
    main: .
    binary: infai
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: darwin-arm64
    main: .
    binary: infai
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: infai
    binaries:
      - infai
    repository:
      owner: dipankardas011
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/dipankardas011/infai"
    description: "Zero-management launch templates for llama.cpp"
